
/**
 * Home模块常量
 */
export const constants={

    /**
     * navibar size change
     */
    NAVIBAR_WIDTH_CHANGED:"NAVIBAR_WIDTH_CHANGED",  

    NAVIBAR_HEIGHT_CHANGED:"NAVIBAR_HEIGHT_CHANGED",

    CUSTOMER_LIST_Height_CHANGED:"CUSTOMER_LIST_Height_CHANGED",
     
    CUSTOMER_LIST_WIDTH_CHANGED:"CUSTOMER_LIST_WIDTH_CHANGED",
    
    CUSTOMER_LIST_INIT_SIZE:"CUSTOMER_LIST_INIT_SIZE",

    CHAT_WIDTH_CHANGE:'CHAT_WIDTH_CHANGE',

    CHAT_WIDTH_QUERY:'CHAT_WIDTH_QUERY',
}

