export const constants = {

     
    LOAD_HISTORY_MESSAGE:'LOAD_HISTORY_MESSAGE',

    LOAD_OFFLINE_MESSAGE:'LOAD_RECENT_MESSAGE',

    

    RECEIVE_MESSAGE:'RECEIVE_MESSAGE',

    SHOW_DETAIL_HISTORY_MESSAGE:'SHOW_DETAIL_HISTORY_MESSAGE',

    CLOSE_DETAIL_HISTORY_MESSAGE:'CLOSE_DETAIL_HISTORY_MESSAGE',
 
}